import Head from 'next/head';
import { useRouter } from 'next/router';
import React from 'react';
import { Footer } from '../../src/core/components/footer';
import { NavBar } from '../../src/core/components/navbar';
import { productData } from '../../src/core/data/productData';
import { Product } from '../../src/core/models/product';
import { ProductDetail } from '../../src/packages/product/containers';
interface ProductDetailPageProps {}

const defaultProduct: Product = {
    id: '',
    category: '',
    description: '',
    name: '',
    price: -1,
    images: [],
};

const ProductDetailPage: React.FC<ProductDetailPageProps> = () => {
    const router = useRouter();
    const { id } = router.query;
    const [product, setProduct] = React.useState<Product>(defaultProduct);

    React.useEffect(() => {
        let productDB = productData.find((item) => item.id === id);
        setProduct(productDB!);
    }, [id]);

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <NavBar />

            <ProductDetail product={product} />
            <Footer />
        </>
    );
};

export default ProductDetailPage;
