import { NextPage, NextPageContext } from 'next';
import Head from 'next/head';
import React from 'react';
import { Layout } from '../../src/packages/product/components/layout';
import { ProductFullList } from '../../src/packages/product/containers';
interface ProductFullListPageProps {
    category: string;
}

const ProductFullListPage: NextPage<ProductFullListPageProps> = ({ category }) => {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Layout>
                <ProductFullList category={category} />
            </Layout>
        </>
    );
};

ProductFullListPage.getInitialProps = async (ctx: NextPageContext): Promise<ProductFullListPageProps> => {
    let props = { category: ctx.query.category || '' };
    return props as ProductFullListPageProps;
};

export default ProductFullListPage;
