import Head from 'next/head';
import React from 'react';
import { Footer } from '../../src/core/components/footer';
import { NavBar } from '../../src/core/components/navbar';
interface ProductFullListPageProps {}

const ProductFullListPage: React.FC<ProductFullListPageProps> = () => {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <NavBar />
            <Footer />
        </>
    );
};

export default ProductFullListPage;
