import type { NextPage } from 'next';
import Head from 'next/head';
import { NavBar } from '../src/core/components/navbar';
import { ProductHome } from '../src/packages/product/containers';

const Home: NextPage = () => {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div>
                <NavBar />
                <ProductHome />
            </div>
        </>
    );
};

export default Home;
